name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint src --ext .js,.jsx,.ts,.tsx

      - name: Build project
        run: npm run build